name: Inbox Bot

"on":
  workflow_dispatch:
    inputs:
      debug:
        description: "Debug logging"
        type: boolean
        required: true
        default: false
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run:
    uses: ./.github/workflows/dashboard.yml
    with:
      mode: inbox
      headless: true
      debug: ${{ github.event.inputs.debug == 'true' }}
    secrets: inherit
