name: Message Bot

on: []

jobs:
  run:
    uses: ./.github/workflows/dashboard.yml
    with:
      mode: msg
      max_items: ${{ github.event.inputs.max_items || '' }}
      headless: true
      debug: ${{ github.event.inputs.debug == 'true' }}
    secrets: inherit
